[package]
name = "fstracer"
version = "0.1.0"
edition = "2021"
rust-version = "1.56"
license = "GPL-3.0-or-later"

[lib]
name = "fstracer"
path = "fstracer.rs"
crate-type = ["cdylib"]

[dependencies]
libc = "0.2"
once_cell = "1.8"
